### ISSUE TITLE
Problems during installation

### ISSUE THREAD

**Issue by piaopiaojie** [PlotJuggler/plotjuggler-ros-plugins#14]
when I run ` sudo apt install ros-${ROS_DISTRO}-plotjuggler-ros`
I got : 
```
 ros-kinetic-plotjuggler : Depends: binutils-dev but it is not going to be installed
                       Depends: libqt5multimedia5-plugins but it is not going to be installed
```
but when I install those two depends.
` binutils is already the newest version (2.26.1-1ubuntu1~16.04.8) `
` libqt5multimedia5-plugins : Depends: libqt5multimedia5 (= 5.2.1-0ubuntu5) but 5.5.1-4ubuntu2 is to be installed ` 
So , how can I install this tool?
build with repository is wrong,too.

**Comment by piaopiaojie** [comment]
sudo apt install ros-kinetic-plotjuggler-ros

**Comment by piaopiaojie** [comment]
Anyone can help me?

**Comment by facontidavide** [comment]
Sorry, but since Kinetic is EOL, I am not goingto investigate or fix this. 

Furthermore, I think it might be a problem that is directly related to your particular installation.

**Comment by piaopiaojie** [comment]
we can solve it from a new software source on ubuntu.
Thanks a lot!
