### ISSUE TITLE
Update data tip of each plot according to the header stamp rather than the receive stamp when `use_header_stamp` is true

### ISSUE THREAD

**Issue by zchenpds** [PlotJuggler/plotjuggler-ros-plugins#15]
When `use_header_stamp` is set to `true` for plugin`DataLoad ROS bags`,  ROS Topic Re-Publisher still uses the receive/record timestamp to determine which message to publish, which creates a **discrepancy** between the messages published and the data tip shown in the plot. The figure below shows the discrepancy: a) header timestamp; b) receive/record timestamp.
![image](https://user-images.githubusercontent.com/10326250/119739226-e6deff80-be4f-11eb-908e-86a56ad5a8c7.png)
Can we show the data tip of the plotted data point corresponding to the header stamp instead?

**Comment by facontidavide** [comment]
I just fixed this. Please try and let me know if it works for you

**Comment by zchenpds** [comment]
Thanks a lot! I look forward to the ROS1 fix.
