### ISSUE TITLE
I have some problem in compile from source

### ISSUE THREAD

**Issue by littlewhite428** [PlotJuggler/plotjuggler-ros-plugins#34]
## Environment
**ubuntu16.04
ros kinetic 
gcc-8
qt-5**
## command
`cd ~/ws_plotjuggler`
`rosdep install --from-paths src --ignore-src --rosdistro=${ROS_DISTRO} -y`
`catkin_make`

**then the error occurs:**
ws_plotjuggler/src/PlotJuggler/plotjuggler_plugins/DataStreamWebsocket/websocket_server.cpp:109:11: error: ‘qOverload’ was not declared in this scope
           qOverload<const QString &>(&QComboBox::currentIndexChanged),
           ^~~~~~~~~
ws_plotjuggler/src/PlotJuggler/plotjuggler_plugins/DataStreamWebsocket/websocket_server.cpp:109:21: error: expected primary-expression before ‘const’
           qOverload<const QString &>(&QComboBox::currentIndexChanged),
## Also
if I compile the main package Plotjuggler(ignore the ros-plugin) with `cmake ..` and `make`, the same error occurs.( > _ < )

**Comment by facontidavide** [comment]
Your version of qt is too old.

Ubuntu 16.04 is not supported any more.

**Comment by littlewhite428** [comment]
thanks~
