### ISSUE TITLE
Parsing comma separated values from diagnostics message

### ISSUE THREAD

**Issue by AndreasNagel** [PlotJuggler/plotjuggler-ros-plugins#36]
Hey, opening an issue about an enhancement I would like. I previously opened a [pull request](https://github.com/PlotJuggler/plotjuggler-ros-plugins/pull/32), with a possible solution. The gist of it is, that I would like to see a plot of a list of comma separated values from the diagnostics message (for example a diagnostic message with key: acceleration; value: 0.45, 1.0, -0.012).

Would you consider looking at this PR?

**Comment by facontidavide** [comment]
I am afraid this change is too specific for you use case, since this syntax is not broadly used in the ROS community.

In the future (maybe near) I am planning to make easier to build custom parsers with LUA, but for the time being, I am afraid that you need to work with your own fork.
