### ISSUE TITLE
Plot custom ROS2 messages

### ISSUE THREAD

**Issue by nehamaerez** [PlotJuggler/plotjuggler-ros-plugins#39]
Hi,
I have some custom ROS (2) messages that I would like to plot in plotjuggler.
Currently, I can see my topics but nothing happens when I select them. Of course, standard ROS messages are working fine (geometry_msgs etc.).
I'm sourced both to my workspace where my messages are defined, and to /opt/ros/galactic/setup.bash

Could you recommend the best way to add my custom messages?

**Comment by facontidavide** [comment]
It is supposed to work, IF you sourced your workspace with message definition. Can you provide a way to replicate this error on my side?
