### ISSUE TITLE
Installation from apt missing for galactic

### ISSUE THREAD

**Issue by mstoelzle** [PlotJuggler/plotjuggler-ros-plugins#45]
Since this morning (we have a continuous CI, which runs every morning), the installation of the plotjuggler ros package for the `galactic` distribution is failing. When I am trying to run:
```bash
sudo apt install ros-galactic-plotjuggler-ros
```
it fails with the error that it is unable to locate the package.

**Comment by facontidavide** [comment]
I am aware of the issue. I need to find time to address it.

**Comment by facontidavide** [comment]
solved (waiting for next sync

**Comment by mstoelzle** [comment]
> solved (waiting for next sync

Thank you for having a look at this issue. Currently, the problem is still persisting - is this normal as the sync has not happened yet?
