### ISSUE TITLE
Segmentation Fault by loading Layout with tab separations

### ISSUE THREAD

**Issue by PSotiriadis** [PlotJuggler/plotjuggler-ros-plugins#62]
# Problem description
Receive "Segmentation fault" trying to load saved layout, which contains vertical or horizontal tab separations. Launching plotjuggler and loading layout without tab separations, is working without problems. 

# Steps to reproduce (important)
**- Describe your platform / Operative System.**
  Ubuntu 22.04 with ROS2 Humble.

**- Check if the problem can be reproduced using the dummy data created by the command line argument "-t" or one of the files in the folder "datasamples".**
  Yes, I also receive "Segmentation Fault" Error! 
  In details, I start plotjuggler using "ros2 run plotjuggler plotjuggler -t" and I save the following layout under name jugplot.xml
<img width="1881" alt="image" src="https://user-images.githubusercontent.com/47846833/217051586-87772bf6-510c-44dd-a5f6-f0cce65cd64a.png">
I stop plotjuggler and call it again with "ros2 run plotjuggler plotjuggler". Then from 'File->Layout->load Data and Window plots layout' I try to load my jugplot.xml layout and I receive:
<img width="896" alt="image" src="https://user-images.githubusercontent.com/47846833/217052527-65bc4cda-93ba-49b8-a392-189171431f16.png">

**Comment by RCMast3r** [comment]
I am having the same issue

**Comment by facontidavide** [comment]
I hope to have time investigating this during the weekend

**Comment by federicociresola** [comment]
Hi,
I have the same problem with the same setup ROS2-Humble on Ubuntu 22.04. 
I am using version 3.7.1 which I downloaded from the official ROS repositories.

**Comment by alexbuyval** [comment]
Hi,

I have the same issue too. 
![image](https://github.com/PlotJuggler/plotjuggler-ros-plugins/assets/2115811/7537ad76-32c8-4775-b1e3-b892ac46cfeb)

**Comment by facontidavide** [comment]
To all of you folks. Can you PLEASE give me something that I can run on my computer to reproduce this?

Preferably a rosbag + the incriminated layout XML

**Comment by alexbuyval** [comment]
@facontidavide I hope it will be helpful.
However almost all messages are not standard in bag file. If it is critical let me know and I'll prepare another bag file.
[rosbag2_2023_07_07-13_52_21.zip](https://github.com/PlotJuggler/plotjuggler-ros-plugins/files/11985350/rosbag2_2023_07_07-13_52_21.zip)
[plot_mppi_resid.zip](https://github.com/PlotJuggler/plotjuggler-ros-plugins/files/11985353/plot_mppi_resid.zip)

**Comment by scrice** [comment]
Still experiencing this issue on Windows 10 wsl2 Ubuntu 22.04 Humble.
Version 3.7.1 installed via "sudo apt install ros-humble-plotjuggler-ros"

**Comment by DavideLanzoniSacmi** [comment]
> # Problem description
> Receive "Segmentation fault" trying to load saved layout, which contains vertical or horizontal tab separations. Launching plotjuggler and loading layout without tab separations, is working without problems.
> 
> # Steps to reproduce (important)
> **- Describe your platform / Operative System.** Ubuntu 22.04 with ROS2 Humble.
> 
> **- Check if the problem can be reproduced using the dummy data created by the command line argument "-t" or one of the files in the folder "datasamples".** Yes, I also receive "Segmentation Fault" Error! In details, I start plotjuggler using "ros2 run plotjuggler plotjuggler -t" and I save the following layout under name jugplot.xml <img alt="image" width="1881" src="https://user-images.githubusercontent.com/47846833/217051586-87772bf6-510c-44dd-a5f6-f0cce65cd64a.png"> I stop plotjuggler and call it again with "ros2 run plotjuggler plotjuggler". Then from 'File->Layout->load Data and Window plots layout' I try to load my jugplot.xml layout and I receive: <img alt="image" width="896" src="https://user-images.githubusercontent.com/47846833/217052527-65bc4cda-93ba-49b8-a392-189171431f16.png">

Same exact error

**Comment by azurechen1203** [comment]
@facontidavide: Having the same issue as well. The segmentation fault showed up even without data.

## Steps to reproduce:

**Platofrm/operative system:** Ubuntu 22.04 with ROS2 Humble

**Steps:** 
1. ros2 run plotjuggler plotjuggler
2.  right click -> split vertically
3. click save window/plot layout
4. close tab1
5. on tab2, load the .xml file

[Screencast from 21-12-23 11:25:28.webm](https://github.com/PlotJuggler/plotjuggler-ros-plugins/assets/141415841/4a6209a1-9215-48f2-9841-2f413850ac24)


**Results:**
Plotjuggler unexpectedly closed with the following error message:

![Screenshot from 2023-12-21 11-26-36](https://github.com/PlotJuggler/plotjuggler-ros-plugins/assets/141415841/89935814-56f0-402a-9358-3372f1a86835)

**Note: **
The error doesn't happen if not splitting the plot.

**Comment by azurechen1203** [comment]
Sorry, how could I update it to 3.8.4?

**Comment by azurechen1203** [comment]
Yeah! Already tried that but it's still 3.8.1

![Screenshot from 2024-01-04 15-20-04](https://github.com/PlotJuggler/plotjuggler-ros-plugins/assets/141415841/16073bf6-95e2-4f63-bfb2-bf6e9e6a39e2)

**Comment by facontidavide** [comment]
which version of ROS are you using?
You must wait for the release; I am afraid

**Comment by PSotiriadis** [comment]
I updated my system today, plotjuggler is updated to V3.8.5 and the problem no longer exists. Thank you @facontidavide 👍
