### ISSUE TITLE
Plotjuggler on humble interprets Odometry message incorrectly

### ISSUE THREAD

**Issue by PaulBouchier** [PlotJuggler/plotjuggler-ros-plugins#79]
Weird problem manifests on both x86 and arm versions of ros-humble-plotjuggler (with ros-humble-plotjuggler-ros plugin). Plotjuggler is messing up the definition of the Odometry message as shown in the image. 

![ksnip_20240121-171854](https://github.com/PlotJuggler/plotjuggler-ros-plugins/assets/2617681/fa0fd2f3-864d-4135-b9b6-fa64f0f3afa2)

I'm publishing Odometry on /odom and ros2 topic info shows me so:
ros2_rpi:ros2_ws$ ros2 topic info /odom
Type: nav_msgs/msg/Odometry

Yet plotjuggler shows pose.pose.orientation as having fields: pitch, roll, x, y, yaw, and z. Missing is w, and the Odometry message doesn't have the euler fields in it.

When I capture a ros2 bag and look at /odom in plotjuggler, pose.pose.position.z contains what should be in pose.pose.position.x, and pose.pose.orientation.x contains what should be in pose.pose.position.y. It looks as if the Odometry message is corrupt in the plotjuggler plugin. I've tried this on x86 Ubuntu 22.04 (humble) with the same results. 

rqt_bag shows the fields correctly, so the problem is in plotjuggler, not in the bagfile or the message definition.

Does anyone know what's going on?

**Comment by facontidavide** [comment]
duplicated and already fixed
