### ISSUE TITLE
Plotjuggler crashes after subscribing to ROS topic (`Floating point truncated 1`)

### ISSUE THREAD

**Issue by nspo** [PlotJuggler/plotjuggler-ros-plugins#8]
I'm using Plotjuggler 3.0.7 (Snap) on Ubuntu 18.04. Each time I subscribe to a specific ROS topic, Plotjuggler crashes immediately. It's possible other "bad" topics exist that make it crash but I identified at least one that's enough.

How to reproduce:
- Start `roscore`
- Replay bag file with a "bad" topic: `rosbag play -l filename.bag`
- Start ROS subscriber and select the "bad" topic
- Plotjuggler crashes with the attached error messages

[plotjuggler-crash-after-subscribing-ROS-topic.txt](https://github.com/PlotJuggler/plotjuggler-ros-plugins/files/5873251/plotjuggler-crash-after-subscribing-ROS-topic.txt)

A similar thing happens when trying to open the bag file directly without streaming and selecting the topic. In this case it catches the exception though:

![plotjuggler-error-when-selecting-many-messages-from-bag](https://user-images.githubusercontent.com/1850504/105845287-d53d3680-5fda-11eb-926a-c1507097a7f0.png)

**Comment by facontidavide** [comment]
Ok. It is NOT supposed to crash (I need to fix this), but probably this is a duplicated issue:

https://github.com/facontidavide/PlotJuggler/issues/325

**Comment by nspo** [comment]
In case this has the same root cause (data in bag cannot be displayed due to integer values needing too many bits), would it not make sense to optionally allow this ("Allow integer adulteration? [yes/no]")?

**Comment by facontidavide** [comment]
ploblem should be fixed

**Comment by nspo** [comment]
Great, thanks! Can't verify yet as the snap is still on 3.0.7 but will do when it's updated.
